global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'number'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'book'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
